name: decision dice

on:
  push:
    branches: [ main ]

jobs:
  cluster:
    name: Deploy decision dice to AWS
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      id: credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    #- name: Deploy to AWS CloudFormation
    #  uses: aws-actions/aws-cloudformation-github-deploy@v1
    #  with:
    #    name: decision-dice
    #    template: template.yaml
#        parameter-overrides: "MyParam1=myValue,MyParam2=${{ secrets.MY_SECRET_VALUE }}"
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release /p:GenerateRuntimeConfigurationFiles=true
    - name: Package
      run: |
        aws cloudformation package --template-file template.yaml \
            --s3-bucket joshuarichardson-deployment \
            --output-template-file template-packaged.yaml \
            --s3-prefix ${{ github.ref_name }}-${{ github.run_number }}

        aws s3 cp template-packaged.yaml s3://joshuarichardson-deployment/${{ github.ref_name }}-${{ github.run_number }}/

        aws cloudformation create-change-set \
            --template-url https://s3-eu-west-2.amazonaws.com/joshuarichardson-deployment/${{ github.ref_name }}-${{ github.run_number }}/template-packaged.yaml \
            --stack-name decision-dice \
            --change-set-name ${{ github.ref_name }}-${{ github.run_number }}





